(* © 2013, 2014 Ian Eure *)
(* Author: Ian Eure <ian.eure@gmail.com> *)

S = ((<BOL>? (FORCELN | BUS_ADDR | UUT_ADDR))? <EOL>)*

<SEP> = <(" " | "\t")+>
<COMMENT> = "!" #".*"
<BOL> = SEP
<EOL> = SEP? COMMENT? "\n"
<EQ> = (SEP* "=" SEP*)

DEC = #"[0-9]+"
HEX = #"[0-9A-F]+"

STRING = #"[A-Z0-9;@=<>'\.\?#\+\-,%\*\\/\"\$_ ]*"

FORCELN = <"FORCELN" SEP> FORCE_LINE EQ DEC
BUS_ADDR = <"BUSADR" EQ> HEX
UUT_ADDR = <"UUTADR" EQ> HEX

FORCE_LINE = ("BR/ACK" | "BUSREQ" | "BUSRQ" | "DBE" | "DMA" | "HALT" |
              "HOLD" | "INTR" | "MR" | "RDY" | "READY" | "RQGT0" |
              "RQGT1" | "TSC" | "UNUSED" | "WAIT")
