(* © 2013, 2014 Ian Eure *)
(* Author: Ian Eure <ian.eure@gmail.com> *)

S = ((<BOL>? (FORCELN | BUS_TEST_ADDR | RUN_UUT_ADDR))? <EOL>)*

<SEP> = <(" " | "\t")+>
<COMMENT> = "!" #".*"
<BOL> = SEP
<EOL> = SEP? COMMENT? "\n"
<EQ> = (SEP* "=" SEP*)

DEC = #"[0-9]+"
HEX = #"[0-9A-F]+"

STRING = #"[A-Z0-9;@=<>'\.\?#\+\-,%\*\\/\"\$_ ]*"

FORCELN = <"FORCELN" SEP> ("BR/ACK" | "BUSREQ" | "BUSRQ" | "DBE" | "DMA" | 
                           "HALT" | "HOLD" | "INTR" | "MR" | "RDY" |
                           "READY" | "RQGT0" | "RQGT1" | "TSC" | "UNUSED" |
                           "WAIT") <EQ> DEC
BUS_TEST_ADDR = <"BUSADR" EQ> HEX
RUN_UUT_ADDR = <"UUTADR" EQ> HEX
